// v5.4 ChatGPT analysis export
function sectionSummaryForRecord(r){return SECTIONS.map(s=>{const items=(r.items||[]).filter(x=>x.section===s[0]&&!x.omitted&&x.isCorrect!==null);if(items.length){const c=items.filter(x=>x.isCorrect).length;return `${s[0]}：${c}/${items.length}（${Math.round(c/items.length*100)}%）`}const z=r.meta?.importedSectionStats?.[s[0]];if(Array.isArray(z)&&Number(z[1])>0)return `${s[0]}：${z[0]}/${z[1]}（${Math.round(Number(z[0])/Number(z[1])*100)}%）`;return `${s[0]}：データなし`}).join('\n')}
function difficultySummaryForRecord(r){return ['A','B','C','D'].map(d=>{const a=(r.items||[]).filter(x=>x.difficulty===d&&!x.omitted&&x.isCorrect!==null);if(!a.length)return `難易度${d}：データなし`;const c=a.filter(x=>x.isCorrect).length;return `難易度${d}：${c}/${a.length}（${Math.round(c/a.length*100)}%）`}).join('\n')}
function themeSummaryForRecord(r){const m=themeMap([r]),rows=Object.entries(m).map(([t,v])=>({t,...v,p:Math.round(v.c/v.n*100)})).sort((a,b)=>a.p-b.p||b.n-a.n||a.t.localeCompare(b.t,'ja'));return rows.length?rows.map(x=>`${x.t}：${x.c}/${x.n}（${x.p}%）・誤答${x.miss}回`).join('\n'):'テーマ付き採点データなし'}
function questionLinesForRecord(r){return (r.items||[]).map(x=>{const status=x.omitted?'省略':x.isCorrect===true?'○':x.isCorrect===false?'×':'未採点',themes=(x.themes||[]).length?(x.themes||[]).join(' / '):'-';return `問${x.q}｜${status}｜自分:${x.answer||'-'}｜正答:${x.correct||'-'}｜難易度:${x.difficulty||'-'}｜テーマ:${themes}`}).join('\n')}
function formatOneRecordForChatGPT(r){const z=gradedInfo(r),b=Number(r.meta?.border||0),om=(r.items||[]).filter(x=>x.omitted).length,miss=(r.items||[]).filter(x=>x.isCorrect===false);return `【宅建 過去問・1回分分析データ】\n\n■ 基本情報\n実施日：${r.meta?.date||'-'}\n年度：${r.meta?.year||'-'}\n周回：${r.meta?.round||'-'}周目\n所要時間：${r.meta?.minutes||'-'}分\n得点：${z.den?`${z.c}/${z.den}`:'未採点'}\n正答率：${z.p===null?'-':z.p+'%'}\n合格基準点：${r.meta?.border||'-'}\n判定：${z.den&&b?(z.c>=b?'合格基準以上':`基準まであと${b-z.c}点`):'-'}\n省略：${om}問\n\n■ 分野別\n${sectionSummaryForRecord(r)}\n\n■ 難易度別\n${difficultySummaryForRecord(r)}\n\n■ テーマ別\n${themeSummaryForRecord(r)}\n\n■ 誤答一覧\n${miss.length?miss.map(x=>`問${x.q}｜難易度:${x.difficulty||'-'}｜テーマ:${(x.themes||[]).join(' / ')||'-'}｜自分:${x.answer||'-'}｜正答:${x.correct||'-'}`).join('\n'):'誤答データなし'}\n\n■ 問題別データ\n${questionLinesForRecord(r)}\n\n【ChatGPTへの依頼例】\nこの結果を分析し、得点を伸ばすために優先して復習すべき分野・テーマ、難易度別の課題、次回の学習方針を具体的に教えてください。`}
function cumulativeThemeLines(rs){const m=themeMap(rs),rows=Object.entries(m).map(([t,v])=>({t,...v,p:Math.round(v.c/v.n*100)})).sort((a,b)=>a.p-b.p||b.n-a.n||a.t.localeCompare(b.t,'ja'));return rows.length?rows.map(x=>`${x.t}：出題${x.n}｜正解${x.c}｜誤答${x.miss}｜正答率${x.p}%`).join('\n'):'テーマ付き採点データなし'}
function formatCumulativeForChatGPT(){const rs=sortedRecords().map(x=>x.r),graded=rs.filter(r=>gradedInfo(r).den);if(!graded.length)return null;const infos=graded.map(r=>gradedInfo(r)),latest=infos.at(-1),best=Math.max(...infos.map(z=>z.c)),avgScore=(infos.reduce((a,z)=>a+z.c,0)/infos.length).toFixed(1),avgPct=Math.round(infos.reduce((a,z)=>a+z.p,0)/infos.length),recent=graded.slice(-5);const scoreHistory=graded.map((r,i)=>{const z=gradedInfo(r),b=Number(r.meta?.border||0);return `${i+1}. ${r.meta?.date||'-'}｜${r.meta?.year||'-'}年度 ${r.meta?.round||'-'}周目｜${z.c}/${z.den}（${z.p}%）｜基準${b||'-'}点`}).join('\n');const sections=SECTIONS.map(s=>{const all=sectionPct(graded,s[0]),rec=sectionPct(recent,s[0]),d=rec-all;return `${s[0]}：全期間${all}%｜直近5回${rec}%｜変化${d>0?'+':''}${d}pt`}).join('\n');const diffs=['A','B','C','D'].map(d=>`難易度${d}：全期間${difficultyPct(graded,d)}%｜直近5回${difficultyPct(recent,d)}%`).join('\n');return `【宅建 過去問・累積分析データ】\n\n■ 全体\n採点回数：${graded.length}回\n最新得点：${latest.c}/${latest.den}\n最高得点：${best}点\n平均得点：${avgScore}点\n平均正答率：${avgPct}%\n\n■ 得点推移\n${scoreHistory}\n\n■ 分野別\n${sections}\n\n■ 難易度別\n${diffs}\n\n■ テーマ別累積\n${cumulativeThemeLines(graded)}\n\n【ChatGPTへの依頼例】\nこれまでの累積データを分析し、得点推移、分野・難易度・テーマごとの弱点、最近改善している点と悪化している点を整理してください。そのうえで、40点を目標にした復習優先順位と次の過去問演習で意識すべきことを具体的に提案してください。`}
async function copyAnalysisText(text,label){if(!text)return alert('書き出せる採点済みデータがありません。');try{await navigator.clipboard.writeText(text);alert(`${label}をクリップボードにコピーしました。\nChatGPTに貼り付けて分析できます。`)}catch(e){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();const ok=document.execCommand('copy');ta.remove();if(ok)alert(`${label}をクリップボードにコピーしました。\nChatGPTに貼り付けて分析できます。`);else prompt('下の内容をコピーしてください。',text)}}
window.copyRecordAnalysis=i=>{const r=records()[i];if(r)copyAnalysisText(formatOneRecordForChatGPT(r),'1回分の分析データ')};
window.copyCumulativeAnalysis=()=>copyAnalysisText(formatCumulativeForChatGPT(),'累積分析データ');
function installCumulativeExportButton(){const page=document.querySelector('.page[data-page="5"]');if(!page||$('copyCumulativeAnalysis'))return;const first=page.querySelector('.card');if(!first)return;const row=document.createElement('div');row.className='row';row.style.marginTop='12px';row.innerHTML='<button class="btn primary" id="copyCumulativeAnalysis" type="button">累積データをChatGPT用にコピー</button>';first.appendChild(row);$('copyCumulativeAnalysis').onclick=window.copyCumulativeAnalysis}
function enhancePastExportButtons(){document.querySelectorAll('#pastList .pastCard').forEach(card=>{const actions=card.querySelector('.pastActions');if(!actions||actions.querySelector('.analysisCopyBtn'))return;const detail=actions.querySelector('button[onclick^="showPastDetail"]');const m=detail?.getAttribute('onclick')?.match(/\((\d+)\)/);if(!m)return;const btn=document.createElement('button');btn.className='btn secondary analysisCopyBtn';btn.type='button';btn.textContent='ChatGPT用にコピー';btn.onclick=()=>window.copyRecordAnalysis(Number(m[1]));actions.insertBefore(btn,actions.lastElementChild)})}
const _renderPastResultsV54=renderPastResults;renderPastResults=function(){_renderPastResultsV54();enhancePastExportButtons()};
const _showPastDetailV54=window.showPastDetail;window.showPastDetail=i=>{_showPastDetailV54(i);const host=$('pastDetail');if(!host||$('detailAnalysisCopy'))return;const btn=document.createElement('button');btn.className='btn primary';btn.id='detailAnalysisCopy';btn.type='button';btn.style.width='100%';btn.style.marginBottom='8px';btn.textContent='この回をChatGPT用にコピー';btn.onclick=()=>window.copyRecordAnalysis(i);const danger=host.querySelector('button.danger');if(danger)host.insertBefore(btn,danger);else host.appendChild(btn)};
installCumulativeExportButton();
enhancePastExportButtons();
