// v5.3 per-question default themes
const QUESTION_DEFAULT_THEMES_KEY='takkenQuestionDefaultThemes';
function questionDefaults(){try{const v=JSON.parse(localStorage.getItem(QUESTION_DEFAULT_THEMES_KEY)||'{}');return v&&typeof v==='object'?v:{}}catch(e){return{}}}
function saveQuestionDefaults(v){localStorage.setItem(QUESTION_DEFAULT_THEMES_KEY,JSON.stringify(v))}
function applyQuestionDefaults(){const d=questionDefaults();for(let q=1;q<=50;q++)setSelectedThemes(q,Array.isArray(d[q])?d[q]:[])}
function defaultThemeOptions(q,selected){const sec=sectionOf(q),names=THEMES.filter(t=>t.section===sec).map(t=>t.name);(selected||[]).forEach(t=>{if(!names.includes(t))names.push(t)});return names.sort((a,b)=>a.localeCompare(b,'ja')).map(t=>`<option value="${esc(t)}" ${selected.includes(t)?'selected':''}>${esc(t)}</option>`).join('')}
function renderQuestionDefaults(){const host=$('questionDefaultThemes');if(!host)return;const d=questionDefaults();host.innerHTML=SECTIONS.map(s=>`<div class="defaultThemeSection"><div class="secTitle"><b>${s[0]}</b><span class="badge">問${s[1]}〜${s[2]}</span></div>${Array.from({length:s[2]-s[1]+1},(_,i)=>{const q=s[1]+i,sel=Array.isArray(d[q])?d[q]:[];return `<div class="defaultThemeRow"><label>問${q}</label><select class="control defaultThemeSelect" data-q="${q}" multiple size="${Math.min(3,Math.max(2,sel.length||2))}">${defaultThemeOptions(q,sel)}</select><div class="subtle">複数選択可</div></div>`}).join('')}</div>`).join('');host.querySelectorAll('.defaultThemeSelect').forEach(el=>el.addEventListener('change',()=>{const q=Number(el.dataset.q),next=questionDefaults(),vals=[...el.selectedOptions].map(o=>o.value);if(vals.length)next[q]=vals;else delete next[q];saveQuestionDefaults(next)}))}
function installQuestionDefaultManager(){const page=document.querySelector('.page[data-page="6"]');if(!page||$('questionDefaultThemes'))return;const card=document.createElement('div');card.className='card';card.innerHTML='<h2>問題ごとの初期テーマ</h2><div class="muted">新しい試験を入力するときに自動で入るテーマを設定できます。実際の問題入力では自由に追加・削除できます。複数テーマも設定できます。</div><div id="questionDefaultThemes" style="margin-top:12px"></div>';page.appendChild(card);renderQuestionDefaults()}
// v5.2のリセット処理を拡張し、リセット後に初期テーマを適用する
resetForNextExam=function(){if(!confirm('現在の入力内容をリセットして、次の試験入力を始めますか？\n保存済みの過去結果・正答・統計は削除されません。'))return;document.querySelectorAll('#questions input[type=radio]').forEach(el=>el.checked=false);for(let q=1;q<=50;q++){setSelectedThemes(q,[]);const card=$('q'+q);if(card&&card.dataset.omitted==='1')toggleOmit(q);const manual=$('tm'+q);if(manual)manual.value='';const sel=$('ts'+q);if(sel)sel.value=''}applyQuestionDefaults();const d=new Date();date.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;year.value='';round.value='';border.value='';minutes.value='';answerKey.value='';updateKeyStatus();updateHint();currentResult=null;showPage(0);window.scrollTo({top:0,behavior:'auto'});alert('入力内容をリセットしました。設定済みの初期テーマを反映しています。')};
window.resetForNextExam=resetForNextExam;
const resetBtn=$('resetNextExam');if(resetBtn)resetBtn.onclick=resetForNextExam;
// テーマ候補の編集後は初期テーマ設定の候補も更新する
const _renderThemeManager=renderThemeManager;renderThemeManager=function(){_renderThemeManager();renderQuestionDefaults()};
installQuestionDefaultManager();
