function qHTML(q){return `<article class="qcard" id="q${q}" data-q="${q}" data-omitted="0"><div class="qhead"><div><span class="qnum">問 ${q}</span> <span class="badge">${sectionOf(q)}</span></div><button class="omitBtn" type="button" data-q="${q}">省略</button></div><div class="qbody"><div class="qfield"><span class="label">自分の回答</span><div class="opts">${[1,2,3,4].map(n=>`<input id="a${q}-${n}" name="a${q}" type="radio" value="${n}"><label for="a${q}-${n}">${n}</label>`).join('')}</div></div><div class="qfield"><span class="label">テーマ（複数可）</span><div class="themeControls"><select id="ts${q}" class="themeSelect"></select><button class="btn secondary addThemeToQ" type="button" data-q="${q}">追加</button></div><input id="tm${q}" class="themeManual" placeholder="候補にないテーマを入力してEnter"><div class="selectedThemes" id="selected${q}"></div></div><div class="qfield"><span class="label">難易度</span><div class="opts">${['A','B','C','D'].map(n=>`<input id="d${q}-${n}" name="d${q}" type="radio" value="${n}"><label for="d${q}-${n}">${n}</label>`).join('')}</div></div></div></article>`}
function sortedThemes(q){const s=sectionOf(q),u=usage();return THEMES.slice().sort((a,b)=>{const aSec=a.section===s?0:1,bSec=b.section===s?0:1;if(aSec!==bSec)return aSec-bSec;const au=u[s]?.[a.name]||0,bu=u[s]?.[b.name]||0;if(au!==bu)return bu-au;return a.name.localeCompare(b.name,'ja')})}
function renderThemeSelect(q){const el=$('ts'+q),v=el.value;el.innerHTML='<option value="">テーマを選択</option>'+sortedThemes(q).map(t=>`<option value="${esc(t.name)}">${esc(t.name)}${t.section===sectionOf(q)?'':' — '+esc(t.section)}</option>`).join('');if([...el.options].some(o=>o.value===v))el.value=v}
function renderAllThemeSelects(){for(let q=1;q<=50;q++)renderThemeSelect(q)}
function getSelectedThemes(q){try{return JSON.parse($('q'+q).dataset.themes||'[]')}catch(e){return []}}
function setSelectedThemes(q,arr){$('q'+q).dataset.themes=JSON.stringify([...new Set(arr)]);renderSelectedThemes(q)}
function renderSelectedThemes(q){const arr=getSelectedThemes(q);$('selected'+q).innerHTML=arr.map((t,i)=>`<span class="themeTag">${esc(t)}<button type="button" data-q="${q}" data-i="${i}" aria-label="削除">×</button></span>`).join('');$('selected'+q).querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=getSelectedThemes(q);a.splice(Number(b.dataset.i),1);setSelectedThemes(q,a)})}
function addThemeToQuestion(q,name){name=(name||'').trim();if(!name)return;let a=getSelectedThemes(q);if(!a.includes(name)){a.push(name);setSelectedThemes(q,a)};if(!THEMES.some(t=>t.name===name)){THEMES.push({id:Math.random().toString(36).slice(2),name,section:sectionOf(q)});setThemes();renderAllThemeSelects();renderThemeManager()}$('tm'+q).value='';$('ts'+q).value=''}
function toggleOmit(q){const card=$('q'+q),on=card.dataset.omitted!=='1';card.dataset.omitted=on?'1':'0';card.classList.toggle('omitted',on);card.querySelector('.omitBtn').classList.toggle('on',on);card.querySelector('.omitBtn').textContent=on?'省略中':'省略';card.querySelector('.qbody').classList.toggle('disabledArea',on)}
