window.chooseYear=y=>{year.value=y;updateHint();showPage(0)};window.delKey=y=>{if(!confirm(`${y}年度の正答を削除しますか？`))return;const a=keys();delete a[y];localStorage.setItem('takkenAnswerKeys',JSON.stringify(a));renderKeys();updateHint()};
function collect(k=[]){const items=[];for(let q=1;q<=50;q++){const card=$('q'+q),omitted=card.dataset.omitted==='1'||(k.length===50&&k[q-1]===null);const ans=(document.querySelector(`input[name=a${q}]:checked`)||{}).value||'';const diff=(document.querySelector(`input[name=d${q}]:checked`)||{}).value||'';const themes=getSelectedThemes(q);const correct=k.length?k[q-1]:null;items.push({q,section:sectionOf(q),answer:ans,themes,difficulty:diff,omitted,correct,isCorrect:omitted||!correct||!ans?null:ans===correct})}return{meta:{date:date.value,year:year.value.trim(),round:round.value,border:border.value,minutes:minutes.value},items,createdAt:new Date().toISOString()}}
function bumpUsage(r){const u=usage();r.items.forEach(x=>{if(x.omitted)return;u[x.section]??={};(x.themes||[]).forEach(t=>u[x.section][t]=(u[x.section][t]||0)+1)});localStorage.setItem('takkenThemeUsage',JSON.stringify(u))}
function grade(mode){const y=year.value.trim();if(!y)return alert('年度を入力してください。');if(!round.value)return alert('何周目か入力してください。');if(!border.value)return alert('合格基準点を入力してください。');let k=[];if(mode==='saved'){k=keys()[y]||[];if(k.length!==50)return alert(`${y}年度の正答が登録されていません。`)}if(mode==='paste'){k=parseKey();if(k.length!==50)return alert('50問分の正答を貼り付けてください。削除問題は「-」で位置を残してください。')}const r=collect(k);if(!r.items.some(x=>x.answer||x.themes.length||x.difficulty||x.omitted))return alert('少なくとも1問入力してください。');const list=records();list.push(r);localStorage.setItem('takkenRecords',JSON.stringify(list));bumpUsage(r);currentResult=r;renderResult(r);renderPastResults();renderStatistics();renderAllThemeSelects();showPage(3)}
function pct(c,n){return n?Math.round(c/n*100):0}function metric(label,c,n){const p=pct(c,n);return `<div class="metric"><div class="metricHead"><b>${esc(label)}</b><span>${n?`${c}/${n}（${p}%）`:'対象なし'}</span></div><div class="bar"><span style="width:${p}%"></span></div></div>`}
function renderResult(r){const eligible=r.items.filter(x=>!x.omitted),graded=eligible.filter(x=>x.isCorrect!==null),c=graded.filter(x=>x.isCorrect).length,b=Number(r.meta.border||0),den=graded.length,om=r.items.filter(x=>x.omitted).length;resultSummary.className='';resultSummary.innerHTML=`<div class="stats"><div class="stat">得点<b class="bigScore">${den?c:'-'}/${den||eligible.length}</b></div><div class="stat">合格基準<b>${b||'-'}点</b><div>${den?(c>=b?`基準 +${c-b}点`:`あと ${b-c}点`):'未採点'}</div></div><div class="stat">年度<b>${esc(r.meta.year)}</b></div><div class="stat">省略<b>${om}問</b></div></div>`;sectionStats.className='';sectionStats.innerHTML=SECTIONS.map(s=>{const a=graded.filter(x=>x.section===s[0]);return metric(s[0],a.filter(x=>x.isCorrect).length,a.length)}).join('');difficultyStats.className='';difficultyStats.innerHTML=['A','B','C','D'].map(d=>{const a=graded.filter(x=>x.difficulty===d);return metric(`難易度 ${d}`,a.filter(x=>x.isCorrect).length,a.length)}).join('');const m={};graded.filter(x=>!x.isCorrect).forEach(x=>(x.themes||[]).forEach(t=>m[t]=(m[t]||0)+1));const a=Object.entries(m).sort((x,y)=>y[1]-x[1]);currentWeak.className='';currentWeak.innerHTML=a.length?`<div class="table"><table><tr><th>テーマ</th><th>誤答数</th></tr>${a.map(([t,n])=>`<tr><td>${esc(t)}</td><td>${n}</td></tr>`).join('')}</table></div>`:'<div class="empty">テーマ付きの誤答はありません。</div>'}

function gradedInfo(r){const g=(r.items||[]).filter(x=>!x.omitted&&x.isCorrect!==null),c=g.filter(x=>x.isCorrect).length;if(g.length)return{g,c,den:g.length,p:Math.round(c/g.length*100),imported:false};const ic=Number(r.meta?.importedScore),id=Number(r.meta?.importedDen);if(Number.isFinite(ic)&&Number.isFinite(id)&&id>0)return{g:[],c:ic,den:id,p:Math.round(ic/id*100),imported:true};return{g:[],c:0,den:0,p:null,imported:false}}
function sortedRecords(){return records().map((r,i)=>({r,i})).sort((a,b)=>{const da=a.r.meta?.date||a.r.createdAt||'',db=b.r.meta?.date||b.r.createdAt||'';return da.localeCompare(db)||String(a.r.createdAt||'').localeCompare(String(b.r.createdAt||''))})}
