function sectionPct(rs,section){const vals=rs.map(r=>sectionRecordPct(r,section)).filter(v=>v!==null);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0}
function difficultyPct(rs,d){const a=rs.flatMap(r=>(r.items||[]).filter(x=>x.difficulty===d&&!x.omitted&&x.isCorrect!==null));return a.length?Math.round(a.filter(x=>x.isCorrect).length/a.length*100):0}
function themeMap(rs){const m={};rs.forEach(r=>(r.items||[]).forEach(x=>{if(x.omitted||x.isCorrect===null)return;(x.themes||[]).forEach(t=>{m[t]??={n:0,c:0,miss:0};m[t].n++;if(x.isCorrect)m[t].c++;else m[t].miss++})}));return m}
function renderThemeStats(all,recent){const a=themeMap(all),b=themeMap(recent);const rows=Object.entries(a).map(([t,v])=>({t,...v,p:Math.round(v.c/v.n*100),rp:b[t]?.n?Math.round(b[t].c/b[t].n*100):null})).sort((x,y)=>y.n-x.n||x.p-y.p);themeStatsAll.className='';themeStatsAll.innerHTML=rows.length?`<div class="table"><table><tr><th>テーマ</th><th>出題</th><th>全期間</th><th>直近5回</th></tr>${rows.map(x=>`<tr><td>${esc(x.t)}</td><td>${x.n}</td><td>${x.p}%</td><td>${x.rp===null?'-':x.rp+'%'}</td></tr>`).join('')}</table></div>`:'<div class="empty">テーマ付き採点データがありません。</div>'}
function renderWeakRanking(rs){const m=themeMap(rs),recent3=rs.slice(-3),m3=themeMap(recent3),rows=Object.entries(m).map(([t,v])=>{const recentMiss=m3[t]?.miss||0,p=Math.round(v.c/v.n*100),score=v.miss*2+recentMiss*3+(p<60?2:0)+(v.n>=3?1:0);return{t,...v,p,recentMiss,score}}).filter(x=>x.miss>0).sort((a,b)=>b.score-a.score||b.miss-a.miss).slice(0,10);weakRanking.className='';weakRanking.innerHTML=rows.length?rows.map((x,i)=>`<div class="pastCard"><div><span class="rankNum">${i+1}</span><b>${esc(x.t)}</b></div><div class="muted" style="margin-top:7px">累計 ${x.miss}/${x.n}回ミス・正答率 ${x.p}%${x.recentMiss>=2?`・<span class="scoreBad">直近3回で${x.recentMiss}回ミス</span>`:''}</div></div>`).join(''):'<div class="empty">テーマ付きの誤答データがありません。</div>'}

function addManagedTheme(){const name=newTheme.value.trim(),section=newThemeSection.value;if(!name)return;if(THEMES.some(t=>t.name===name))return alert('同じ名前のテーマがすでにあります。');THEMES.push({id:Math.random().toString(36).slice(2),name,section});newTheme.value='';setThemes();renderThemeManager();renderAllThemeSelects()}
function renderThemeManager(){themeManager.innerHTML=THEMES.slice().sort((a,b)=>a.section.localeCompare(b.section,'ja')||a.name.localeCompare(b.name,'ja')).map(t=>`<div class="managerRow" data-id="${esc(t.id)}"><input class="mName" value="${esc(t.name)}"><select class="mSection">${SECTIONS.map(s=>`<option ${s[0]===t.section?'selected':''}>${s[0]}</option>`).join('')}</select><button class="btn danger mDelete" type="button">削除</button></div>`).join('');themeManager.querySelectorAll('.managerRow').forEach(row=>{const id=row.dataset.id,name=row.querySelector('.mName'),sec=row.querySelector('.mSection');const save=()=>{const t=THEMES.find(x=>x.id===id);if(!t)return;const old=t.name,newName=name.value.trim();if(!newName){name.value=old;return}if(newName!==old&&THEMES.some(x=>x.id!==id&&x.name===newName)){alert('同じ名前のテーマがあります。');name.value=old;return}t.name=newName;t.section=sec.value;setThemes();renderAllThemeSelects()};name.addEventListener('change',save);sec.addEventListener('change',save);row.querySelector('.mDelete').onclick=()=>{const t=THEMES.find(x=>x.id===id);if(!confirm(`「${t?.name||''}」を候補から削除しますか？\n過去の記録は消えません。`))return;THEMES=THEMES.filter(x=>x.id!==id);setThemes();renderThemeManager();renderAllThemeSelects()}})}
function boot(){try{build()}catch(e){console.error('Boot error:',e);const p=document.getElementById('pages');if(p)p.innerHTML='<section class="page active"><div class="card"><h2>起動エラー</h2><div class="muted">画面の初期化でエラーが発生しました。ページを再読み込みしても直らない場合は、この表示のスクリーンショットを送ってください。</div></div></section>'}}
boot();
